language: node_js
node_js:
- '16.18.1'
env:
  global:
  - MATTERMOST_CHANNEL=publication
  # REGISTRY_TOKEN(editor=cozy, app=malakoffmederic)
  - secure: FqzTMmz8YYL5HFVuNxsaCieeAV9ihJcH9o0RBFQ/THR3S4QbEPLGZm+wzsdTa8cBLKdKINtODsC8yJ8HsgdNViJGe6jFTYGTl/0eEyjRBVJqqREu17jT8kgK7GXpwFSKTNXXUF9BNysLaJF0xVd1zhn1iumfbGo3J5PJ8ojcQZBxGz5XW3xduc8NSKOPmjDixUc/FL/5q3m9TihyogbM455L+8G3foTANXS0gDeau6ZcC2BdsC2gSe14rxo1+BvvHk4TuPF/adyU2kxxikjjY2rH/A2s2qvLdXiDPea3HKWjp0c765+expZBFwZDT7SyPoT2mouU8Chmh6D2ORpHRDPVPcwXHcaL0bjusDznvAt+I+KMODupbmcdG18NpMNIAYF1T+dkwswyTzMt5yowoO0+qOU7QnklNE+gIbKjiNpcWOStxZm7ltpxwvtg2W0I3uOme1/V3N4yoTfuWf95tbfD4b92mM876mY4HgsybovY6bB0oVevM27ED3LnNWXTt6FuH1gR08482Fd+iF1o6iKIxFACqTHDJtmO2quGsZjUfv+ND+lRFYeYaAdUcX4WavjWqdtil7ic1U6tIdFz6RGOwcNMhnVJlAMjY5DUoy7MRiie09g/DDu+A+yxS2hYI97zcV+wM+/e4Fg/WZtww62ytoEp3cHEknrhG9m2N5Q=
  # MATTERMOST_HOOK_URL
  - secure: ZTrwQs/6qrXZ+OZMLe15VirsoM2hfQBqgcjNu9ZnPgHkHISaC0sdWG+oFJ8Vm2u87DYmli0SFfPsEQOVyoOIKIrqqUa9F8Thf+Y/zOi5wCqK0rxCODMZ0VP/EUkyN4zXuODlQmX1Cx7PV0LpMp7lW/B9Gs8Wfxkhpkh/BH+8zTGmBP7ZQJOWP1xnruonvx+3imJwkv5dNRJClDcLprSjlqWKrFIJgxdxO5I/fqGQ0aJ6oeSR/J8RglpHtpQ3GEJU3Xoud+Wp5GsnoMAm8Q7ZMzh9v2QuFlVukGvP6ZR7RAst7YhdTmPH4UtY6EsVIiHfGLcfOxEy1yzDFkPFfDCLR1XUQpgbv0Rst67voYdnRG2eMDZx/lSstnehBMvLJCPop4VpyV/+FEN6n2IdH+jhHpwspyS0gBNp352R//Q2nz4E7yamenw59NVV8EZRT0VUDlofWKWrW71UQeA+ZDmMYKG9kiwaixLUv1DyNCFzb397vgIkzj6ol75zAJRH9FHp527Y8LUDAjCMEe/oJNtgKp8dgHgg7MjQWMAqJGPSVJaFQAeoa4zRdpysEb8w6VmEl0G9euod2W4akYhMswAn/lchxBImpbCWH5SiCKmbXxYlWPEMA1aI43BApvRNa8Z/J9psgi83EHQNn769CMeXc8zajv/4XMpF7ifjhaR5Ag8=
cache:
  yarn: true
  directories:
  - node_modules
branches:
  except:
  - build
  - build-debug
script:
- yarn lint
- yarn build
deploy:
- provider: script
  skip-cleanup: true
  script: DEPLOY_BRANCH=build yarn deploy && yarn cozyPublish
  on:
    branch: master
- provider: script
  skip-cleanup: true
  script: DEPLOY_BRANCH=build yarn deploy && yarn cozyPublish --postpublish mattermost
  on:
    tags: true
before_install:
- openssl aes-256-cbc -K $encrypted_1fece3009759_key -iv $encrypted_1fece3009759_iv
  -in github_deploy_key.enc -out /tmp/github_deploy_key -d
- eval "$(ssh-agent -s)"
- chmod 600 /tmp/github_deploy_key
- ssh-add /tmp/github_deploy_key
after_deploy:
- rm /tmp/github_deploy_key
- ssh-add -D
